create table if not exists public.users (
  id bigint generated by default as identity primary key,
  open_id varchar(64) not null unique,
  name text,
  email varchar(320),
  login_method varchar(64),
  role varchar(16) not null default 'user' check (role in ('user', 'admin')),
  community_role varchar(16) not null default 'Doador' check (community_role in ('Doador', 'Catador')),
  phone varchar(32),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.collection_points (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references public.users(id) on delete cascade,
  name varchar(160) not null,
  neighborhood varchar(120) not null,
  address varchar(255) not null,
  opening_hours varchar(160) not null,
  description text not null,
  estimated_volume varchar(80) not null default 'Não informado',
  photo_url varchar(1024),
  latitude numeric(10, 7) not null check (latitude between -90 and 90),
  longitude numeric(10, 7) not null check (longitude between -180 and 180),
  capacity_status varchar(16) not null default 'ativo' check (capacity_status in ('ativo', 'proximo', 'lotado')),
  approval_status varchar(16) not null default 'pendente' check (approval_status in ('pendente', 'aprovado', 'recusado')),
  approved_by_id bigint references public.users(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.point_materials (
  id bigint generated by default as identity primary key,
  point_id bigint not null references public.collection_points(id) on delete cascade,
  material varchar(32) not null check (material in ('Papel', 'Plástico', 'Vidro', 'Metal', 'Eletrônicos')),
  unique (point_id, material)
);

create table if not exists public.point_messages (
  id bigint generated by default as identity primary key,
  point_id bigint not null references public.collection_points(id) on delete cascade,
  author_id bigint not null references public.users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id bigint references public.users(id) on delete set null,
  point_id bigint references public.collection_points(id) on delete set null,
  type varchar(32) not null check (type in ('user_registered', 'profile_updated', 'point_created', 'point_approved', 'point_rejected', 'point_updated', 'point_deleted', 'message_sent')),
  description varchar(300) not null,
  created_at timestamptz not null default now()
);

create index if not exists collection_points_approval_idx on public.collection_points(approval_status);
create index if not exists collection_points_owner_idx on public.collection_points(owner_id);
create index if not exists collection_points_location_idx on public.collection_points(latitude, longitude);
create index if not exists point_materials_point_idx on public.point_materials(point_id);
create index if not exists point_materials_material_idx on public.point_materials(material);
create index if not exists point_messages_point_created_idx on public.point_messages(point_id, created_at);
create index if not exists activity_logs_created_idx on public.activity_logs(created_at);

alter table public.users enable row level security;
alter table public.collection_points enable row level security;
alter table public.point_materials enable row level security;
alter table public.point_messages enable row level security;
alter table public.activity_logs enable row level security;

-- A API usa a service role no servidor; ela ignora RLS. Não exponha SUPABASE_SERVICE_ROLE_KEY no navegador.
